# Generated by Django 4.0.5 on 2022-06-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alumno_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='camada',
            new_name='legajo',
        ),
    ]
